### ISSUE TITLE
Error when using get_time_machine_forecast

### ISSUE THREAD

**Issue by jeffeb3** [microparts/darksky-sdk-python#2]
UnboundLocalError: local variable 'url' referenced before assignment:

```
Traceback (most recent call last):
  File "./mgmt/weather.py", line 25, in <module>
    yesterday
  File "/home/jeffe/home/projects/sprinkler/mgmt/venv/lib/python3.6/site-packages/darksky/api.py", line 35, in get_time_machine_forecast
    exclude=exclude
  File "/home/jeffe/home/projects/sprinkler/mgmt/venv/lib/python3.6/site-packages/darksky/api.py", line 47, in __get_forecast
    url += '{host}/{api_key}/{latitude},{longitude},{time}'.format(
UnboundLocalError: local variable 'url' referenced before assignment
```

Looks like there is a += where there should be an '=' here:
https://github.com/microparts/darksky-sdk-python/blob/master/darksky/api.py#L47

Test code:
```
#!/usr/bin/env python3

from darksky.api import DarkSky
from darksky.types import languages, units, weather

from settings import API

from datetime import datetime, timedelta

darksky = DarkSky(API)

latitude = 39.749668
longitude = -105.216019

yesterday = datetime.now() - timedelta(days=1)
forecast = darksky.get_time_machine_forecast(
    latitude, longitude,
    yesterday
)

print(forecast.daily.data[0].summary)
```

**Comment by Detrous** [comment]
Hi, thank you for your report. I will fix it asap

Sent from ProtonMail Mobile

Вкл пт, авг. 2, 2019 в 22:28, Jeff Eberl <notifications@github.com> пишет:

**Comment by Detrous** [comment]
https://github.com/microparts/darksky-sdk-python/pull/3

**Comment by jeffeb3** [comment]
Can you publish develop to a new version to Pypi? I'm trying to set up a docker to run my sprinklers and it would be nice to be able to just use pip, but I need this fix.

BTW, I've been using this to update my home sprinkler system and it's been working great. Thanks for making this library.
